### ISSUE TITLE
Consider adding jest/prefer-expect-assertions

### ISSUE THREAD

**Issue by tclindner** [tclindner/eslint-config-tc#88]
https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/prefer-expect-assertions.md

**Comment by keisha-rw** [comment]
I'm not a huge fan of this one.  Implementing it will create a lot of noise for something that shouldn't be an issue if we're writing our tests well.  Enforcing the 'expect-expect' rule will make sure our tests have at least one expectation.  The only time I can think of that this would really be handy would be if our expects are done async and we want to make sure they're all called before the test passes.  I'd vote we just hold ourselves accountable to using expect.assertions(n) in those instances rather than enforcing it everywhere.

**Comment by tclindner** [comment]
Sounds great 👍 Closing
